### ISSUE TITLE
Global Prefix

### ISSUE THREAD

**Issue by Multimodcrafter** [nicdard/compiler-design-eth-tests#24]
I like that the tests for HW3 have a prefix variable for where the files are located.

Could we agree to extend this system with a global prefix?

My goal is to have this repository outside of my personal hw directories but be able to access the tests from there.
If we have one global ml file with a prefix variable, which everybody can configure to a value to their liking, the repo could be cloned anywhere, and from then on, updating would be as easy as a pull. Also, for future homeworks, the only setup one needed to do would be to configure the main and makefile.

**Comment by Multimodcrafter** [comment]
I'll happily implement the changes if you don't have the time to do it yourself ;-)

**Comment by nicdard** [comment]
I like the idea, please go ahead and thanks! :)

**Comment by Multimodcrafter** [comment]
see #36

**Comment by nicdard** [comment]
Solved with https://github.com/nicdard/compiler-design-eth-tests/pull/36
