### ISSUE TITLE
Must reference equality really be supported?

### ISSUE THREAD

**Issue by thbwd** [nicdard/compiler-design-eth-tests#39]
@dbernhard-0x7CD's tests include comparing references, for example, in

https://github.com/nicdard/compiler-design-eth-tests/blob/main/05/dbernhard/equality.oat#L25

I wonder, though, whether supporting this is really necessary for this homework. Although the rules **Typ_Eq** and **Typ_Neq** imply that it should be supported, the provided frontend does not implement this (see lines 246 - 252). Also, I did not find any indication anywhere else that we're supposed to add this.

Am I missing something?

**Comment by dbernhard-0x7CD** [comment]
I think we should create a moodle post; I only implemented it because it was possible according to the grammar and TC rules.

**Comment by thbwd** [comment]
It's not necessary: https://moodle-app2.let.ethz.ch/mod/forum/discuss.php?d=93403#p199796
