### ISSUE TITLE
Fibonacci Timeout

### ISSUE THREAD

**Issue by Berke-Ates** [nicdard/compiler-design-eth-tests#6]
The Fibonacci test times out after 5 seconds. My implementation requires at least a minute to complete the test. 
Either my implementation is horrendously slow or yours is quite fast or this test is too ambitious. Could you confirm that you can indeed run this test in the 5 second constraint?

**Comment by nicdard** [comment]
Mine implementation completes It within the allocated time running also the other tests, I do not know however what is the Speed baseline for the project. Also it may depend on the hardware.
